### ISSUE TITLE
Support for IPv6 DNS

### ISSUE THREAD

**Issue by hdbikeroh** [AndrianBdn/wg-cmd#1]
**Is your feature request related to a problem? Please describe.**
On machine with IPv6, the `DNS` settings only reflect an IPv4 address, not the IPv6.
 
**Describe the solution you'd like**
Include the v4 and v6 addresses for DNS

**Describe alternatives you've considered**
Manually retrieved the IPv6 DNS addresses and added them to the configuration.

**Additional context**
Would enable the internet transition to v6.  Love the commander!

**Comment by AndrianBdn** [comment]
Thanks for taking the time to file the issue. Yes, I guess this is something I could plan for the next release.

**Comment by AndrianBdn** [comment]
commit https://github.com/AndrianBdn/wg-cmd/commit/c70f1bfd0f11b6eda494763a4fd236a75fd0ee12 fixes this (mistyped issue number in a commit message)

the new release and binary will be available later this week

**Comment by AndrianBdn** [comment]
Since version [0.1.2](https://github.com/AndrianBdn/wg-cmd/releases/tag/v0.1.2) the Setup Wizard configures IPv6 DNS resolvers addresses (in case IPv6 NAT was enabled). I hope that the feature is implemented correctly and work for you. Please open a new issue if you find a problem.
