### ISSUE TITLE
MTU

### ISSUE THREAD

**Issue by GutsyHeart** [AndrianBdn/wg-cmd#2]
Add MTU setting Client and Server

WG-server
```
[Interface]
...
MTU = 1420
```

WG-peer
```
[Interface]
...
MTU = 1384
```

**Comment by AndrianBdn** [comment]
Thanks for taking the time to file the issue. Makes sense, I will implement this in the nearest release (hopefully this week).

**Comment by AndrianBdn** [comment]
Since version [0.1.2](https://github.com/AndrianBdn/wg-cmd/releases/tag/v0.1.2) it is possible to configure MTU for client and server. I hope that the feature is implemented correctly and work for you. Please open a new issue if you find a problem.
