### ISSUE TITLE
Allow configuration of AllowedIPs in server config

### ISSUE THREAD

**Issue by bradleyg** [AndrianBdn/wg-cmd#4]
**Is your feature request related to a problem? Please describe.**
I have a server (`a`) and 2 clients (`b`,`c`). Client `b` sits on a LAN with many other devices (192.168.1.0/24). I'd like to access those devices (in which WG can't be installed) from client `c` (via the server). To do this in a typical Wireguard configuration (skipping iptables and systcl config for now) you would append the subnet (192.168.1.0/24) to `AllowedIPs` in the server config file for the peer that sits on the LAN (`b`). 

**Describe the solution you'd like**
A way to define `AllowedIPs` for peers, but in the server config file.

**Describe alternatives you've considered**
N/A

**Additional context**
Thank you for this excellent project!

**Comment by AndrianBdn** [comment]
Dear @bradleyg, that you for the feature request. 

Let me describe the approach that I may take for implementing it:
- I will introduce the parameter "ServerRoute" for client config toml files, which will default to an empty string 
- When this parameter is non empty, I am going to append its value to the client's AllowedIP in the server config (besides client's IPv4 and IPv6 addresses which will be there)

Please let me know, does it makes sense for you?

**Comment by bradleyg** [comment]
That would work perfectly 🙏

**Comment by AndrianBdn** [comment]
Great, I think I could implement this in the next point release over this weekend or sooner

**Comment by AndrianBdn** [comment]
@bradleyg please check if the release 0.1.4 implements this feature request correctly. After some thinking I decided to name the configuration parameter AddServerRoute (since it adds, but never overrides)

**Comment by bradleyg** [comment]
Tested, and working great :) 
Thank you!

**Comment by AndrianBdn** [comment]
Thank you @bradleyg !
