### ISSUE TITLE
NAT options don't work without additional firewall rule

### ISSUE THREAD

**Issue by jamespo** [AndrianBdn/wg-cmd#5]
**Describe the bug**
NAT options don't work

**To Reproduce**
1. Create a new tunnel & client
2. Enable NAT 
3. Try and use tunnel
4. Client can't route

**Expected behavior**
Client should be able to route

**Environment (please complete the following information):**
 - OS: Linux
 - Distribution Debian 12
 - Current

**Additional context**

I fixed this by adding "iptables -A FORWARD -o wg0 -j ACCEPT" to PostUp, so the 2 lines for me now look like:

```
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ens18 -j MASQUERADE; iptables -A FORWARD -o wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o ens18 -j MASQUERADE; iptables -D FORWARD -o wg0 -j ACCEPT

```

**Comment by AndrianBdn** [comment]
Thank you for the bug report and for sharing your workaround. I haven't tested WG Commander on Debian 12 yet, and there might be some changes in the default settings compared to Debian 11 that are causing this issue. 

I will investigate this in the coming days. If everything works well, I will release a new version with more explicit iptables commands.

**Comment by jamespo** [comment]
I don't know if this is Debian 12 specific or specific to my WG "server" which is also running docker containers with the rules that involves. Apart from that it's pretty vanilla (behind a firewall/router with NAT).

**Comment by AndrianBdn** [comment]
Indeed, Debian 12 has nothing to do with this. Must be some other iptables rules on your system. However I think that having explicit output rule will not hurt and NAT will work in more cases. I will release 0.1.5 later today. Since you have added the missing lines yourself, you do not need to upgrade (unless you plan to add more interfaces).

**Comment by AndrianBdn** [comment]
Once again, thank you for your report. 

Version 0.1.5 has rules for the output chain (`iptables -A FORWARD -o wg0 -j ACCEPT` and its corresponding command in the PostDown section, as well as equivalent ip6tables rules) by default. Please note that existing configurations will not be automatically updated. 

If you wish to manually update your WG Commander configuration, you can edit the `/etc/wireguard/wgc-wg0/0001-server.toml` file. Just add the missing iptables commands in the PostUp4 and PostDown4 sections.
